# Generated by Django 5.2.4 on 2025-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Добавьте содержание поста', max_length=500, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ImageField(blank=True, help_text='Загрузите превью поста', null=True, upload_to='posts/photo', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_flag',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Укажите название поста', max_length=150, verbose_name='Пост'),
        ),
    ]
