# Generated by Django 5.2.4 on 2025-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication_flag',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
